# Generated by Django 5.1.6 on 2025-03-02 02:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simple_shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customertype',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='customertype',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customertype',
            name='discount_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='customertype',
            name='points_multiplier',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='customertype',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='customertype',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='customertype',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
